version: "3.8"
services:
  website_checker:
    image: "checker:1"
    container_name: "siteprobe_producer"
    env_file:
      - ".env"
    volumes:
      - ./access:/app/access

  availability_handler:
    image: "keeper:1"
    container_name: "siteprobe_consumer_availability"
    env_file:
      - ".env"
    volumes:
      - ./access:/app/access

  content_handler:
    image: "keeper:1"
    container_name: "siteprobe_consumer_content"
    env_file:
      - ".env"
    environment:
      - "MTYPE=content"
    volumes:
      - ./access:/app/access