version: "3.8"
services:
  website_checker:
    image: "checker:1"
    container_name: "siteprobe_producer"
    env_file:
      - ".env"
    environment:
      - "KAFKA_SERVICE_URI=${KAFKA_SERVICE_URI}"
